name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      PLATFORM_NAME: Android
      PLATFORM_VERSION: 11.0
      DEVICE_NAME: Samsung Galaxy S10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Android Emulator in Docker
        run: |
          docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0

      - name: Verify Emulator is Running
        run: |
          for i in {1..30}; do
            if docker exec android-container cat device_status 2>/dev/null; then
              echo "Emulator is ready!"
              exit 0
            fi
            echo "Waiting for emulator to be ready..."
            sleep 5
          done
          echo "Emulator did not start in time" && exit 1

      - name: Start Appium Server in Docker
        run: |
          docker run -d --name appium-server \
            --network=host \
            -p 4723:4723 \
            appium/appium

      - name: Verify Appium Server is Running
        run: |
          for i in {1..30}; do
            if curl -s http://0.0.0.0:4723/wd/hub/status | grep -q '"status":0'; then
              echo "Appium server is ready!"
              exit 0
            fi
            echo "Waiting for Appium server to be ready..."
            sleep 5
          done
          echo "Appium server did not start in time" && exit 1

      - name: Run Tests in a Docker Container
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/workspace \
            -v $HOME/.m2:/root/.m2 \
            -w /workspace \
            maven:3.9.6-eclipse-temurin-17 mvn clean test

      - name: Force Stop Emulator if Stuck
        if: always()
        run: docker rm -f android-container || true