name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLATFORM_NAME: android
      PLATFORM_VERSION: 9.0
      DEVICE_NAME: any

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find available ports
        id: find-ports
        run: |
          EMULATOR_PORT=$(comm -23 <(seq 5554 5584) <(lsof -i -P -n | grep LISTEN | awk '{print $9}' | cut -d: -f2) | shuf -n 1)
          APPIUM_PORT=$(comm -23 <(seq 4723 4753) <(lsof -i -P -n | grep LISTEN | awk '{print $9}' | cut -d: -f2) | shuf -n 1)
          echo "EMULATOR_PORT=$EMULATOR_PORT" >> $GITHUB_ENV
          echo "APPIUM_PORT=$APPIUM_PORT" >> $GITHUB_ENV

      - name: Start Android emulator
        run: |
          docker run --privileged -d -p ${{ env.EMULATOR_PORT }}:5554 -p ${{ env.APPIUM_PORT }}:4723 budtmo/docker-android:emulator_9.0

      - name: Wait for Android emulator to start
        run: |
          sudo apt-get update
          sudo apt-get install -y adb
          adb start-server
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to be ready
        run: |
          boot_completed=""
          while [ -z "$boot_completed" ]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>&1)
            echo "Waiting for emulator to boot..."
            sleep 5
          done
          echo "Emulator booted successfully."

      - name: Verify emulator is running
        run: adb devices

      - name: Start Appium server
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium -p ${{ env.APPIUM_PORT }} &

      - name: Run tests
        run: mvn clean test