name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Android Emulator in Docker
        run: |
          docker run -d --network host -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0

      - name: Verify Emulator is Fully Booted
        run: |
          for i in {1..30}; do
            if [ "$(docker exec android-container adb shell getprop sys.boot_completed 2>/dev/null)" = "1" ]; then
              echo "Emulator is fully booted!"
              exit 0
            fi
            echo "Waiting for emulator to be fully booted..."
            sleep 5
          done
          echo "Emulator did not fully boot in time" && exit 1

      - name: Check Emulator Status
        run: |
          docker exec android-container adb devices | grep emulator | grep -q "device"
          if [ $? -eq 0 ]; then
            echo "Emulator is running"
          else
            echo "Emulator is not running" && exit 1
          fi

      - name: Get Emulator Device ID
        id: get-device-id
        run: |
          EMULATOR_ID=$(docker exec android-container adb devices | grep emulator | cut -f1)
          echo "EMULATOR_ID=$EMULATOR_ID" >> $GITHUB_ENV

      - name: Create Dockerfile for Custom Appium Image
        run: |
          cat <<EOF > Dockerfile
          FROM appium/appium:latest
          RUN appium plugin install --source=npm appium-reporter-plugin
          EXPOSE 4723
          CMD ["appium", "--use-plugins=appium-reporter-plugin"]
          EOF

      - name: Build Custom Appium Docker Image
        run: |
          docker build -t custom-appium .

      - name: Start Appium Container with Plugin
        run: |
          docker run --privileged -d --network host -p 4723:4723 --name appium-container custom-appium

      - name: Print Appium Server Logs
        run: |
          sleep 10  # Wait for the server to start
          docker logs appium-container

      - name: Push monefy apk file into container
        run: |
          docker cp 'com.monefy.app.lite_1.18.0-2208_minAPI21(nodpi)_apkmirror.com.apk' appium-container:/home/androidusr/monefy.apk

      - name: Run Tests in a Docker Container
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}:/workspace \
            -v $HOME/.m2:/root/.m2 \
            -w /workspace \
            -e CI=true \
            -e PLATFORM_NAME=android \
            -e PLATFORM_VERSION=11.0 \
            -e DEVICE_NAME="Samsung Galaxy S10" \
            -e UDID="${EMULATOR_ID}" \
            -e APP_PATH="/home/androidusr/monefy.apk" \
            maven:3.9.6-eclipse-temurin-17 mvn clean test

      - name: Download Test Report
        run: |
          docker exec appium-container curl -o /workspace/report.html http://127.0.0.1:4723/getReport

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html