name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLATFORM_NAME: android
      PLATFORM_VERSION: 9.0
      DEVICE_NAME: any
      EMULATOR_PORT: 5554
      APPIUM_PORT: 4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Android SDK and ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb
          adb version  # Verify ADB installation

      - name: Start Android Emulator in Docker
        run: |
          docker run --privileged -d --name android-emulator \
            -p 5554:5554 -p 5555:5555 -p 4723:4723 \
            budtmo/docker-android:emulator_9.0
          sleep 10  # Give it some time to start
          docker logs android-emulator | tail -n 50  # Check emulator logs

      - name: Wait for Emulator to Boot (Inside Container)
        run: |
          start_time=$(date +%s)
          timeout=300  # 5 minutes

          until docker exec android-emulator adb connect localhost:5555; do
            echo "Waiting for ADB to connect to the emulator..."
            sleep 5
            elapsed=$(( $(date +%s) - start_time ))
            if [[ $elapsed -gt $timeout ]]; then
              echo "Timeout reached! Emulator did not start."
              exit 1
            fi
          done

          echo "Emulator connected, waiting for full boot..."
          start_time=$(date +%s)  # Reset the timer

          until docker exec android-emulator adb shell getprop sys.boot_completed | grep -m 1 "1"; do
            echo "Waiting for emulator to fully boot..."
            sleep 5
            elapsed=$(( $(date +%s) - start_time ))
            if [[ $elapsed -gt $timeout ]]; then
              echo "Timeout reached! Emulator did not fully boot."
              exit 1
            fi
          done
          echo "Emulator is ready."

      - name: Verify Emulator is Running
        run: docker exec android-emulator adb devices

      - name: Start Appium Server in Docker
        run: |
          docker run -d --name appium-server \
            --network=host \
            -p 4723:4723 \
            appium/appium

      - name: Run Tests in a Docker Container
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            maven:3.14.0-openjdk-17 mvn clean test

      - name: Force Stop Emulator if Stuck
        if: always()
        run: docker rm -f android-emulator || true