name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLATFORM_NAME: android
      PLATFORM_VERSION: 9.0
      DEVICE_NAME: any
      EMULATOR_PORT: 5554
      APPIUM_PORT: 4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Android SDK and ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb
          adb version  # Verify ADB installation

      - name: Start Android Emulator in Docker
        run: |
          docker run --privileged -d --name android-emulator \
          -p 5554:5554 -p 5555:5555 -p 4723:4723 \
          budtmo/docker-android:emulator_9.0

      - name: Wait for Emulator to Boot
        run: |
          start_time=$(date +%s)
          timeout=300  # 5 minutes
      
          until adb devices | grep emulator; do
            echo "Waiting for emulator to show up..."
            sleep 5
            elapsed=$(( $(date +%s) - start_time ))
            if [[ $elapsed -gt $timeout ]]; then
              echo "Timeout reached! Emulator did not start."
              exit 1
            fi
          done
      
          export EMULATOR_SERIAL=$(adb devices | grep emulator | awk '{print $1}')
          echo "EMULATOR_SERIAL=$EMULATOR_SERIAL" >> $GITHUB_ENV
      
          until adb -s ${{ env.EMULATOR_SERIAL }} shell getprop sys.boot_completed | grep -m 1 "1"; do
            echo "Waiting for emulator to fully boot..."
            sleep 5
            elapsed=$(( $(date +%s) - start_time ))
            if [[ $elapsed -gt $timeout ]]; then
              echo "Timeout reached! Emulator did not fully boot."
              exit 1
            fi
          done
          echo "Emulator is ready."

      - name: Verify Emulator is Running
        run: adb devices

      - name: Start Appium Server in Docker
        run: |
          docker run -d --name appium-server \
            --network=host \
            -p 4723:4723 \
            appium/appium

      - name: Run Tests in a Docker Container
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            maven:3.14.0-openjdk-17 mvn clean test

      - name: Force Stop Emulator if Stuck
        if: always()
        run: docker rm -f android-emulator || true