name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: budtmo/docker-android:emulator_9.0
        options: --privileged
        ports:
          - 6080:6080
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Appium server
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium &

      - name: Run tests
        run: mvn clean test