name: Android E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Android Emulator in Docker
        run: |
          docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0

      - name: Verify Emulator is Running
        run: docker exec -it android-container cat device_status

      - name: Start Appium Server in Docker
        run: |
          docker run -d --name appium-server \
            --network=host \
            -p 4723:4723 \
            appium/appium

      - name: Run Tests in a Docker Container
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            maven:3.14.0-openjdk-17 mvn clean test

      - name: Force Stop Emulator if Stuck
        if: always()
        run: docker rm -f android-emulator || true